Email:
  protocol: smtp
  hostName: mailhub-vip.ny.ssmb.com
  port: 
  auth: false
  senderAddress: FastFramework@automation.com
  receiverAddress: zl83666@imcnam.ssmb.com
  copyAddress: dm18232@imcnam.ssmb.com
  attachedFileName: 
  attacheHtmlReport: true
  X_Priority: 3
  X_MSMail_Priority: Normal
  X_Mailer: Microsoft Outlook Express 6.00.2900.2869
  X_MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.2869
  ReturnReceipt: 1
